skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
cookie_jar = "Dwd7DXUQHRJaj1suYz6fTcVW7JJqBFVztg1z77t6Ysg"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
