// GENERATED by scripts/gen-relayer-constants.mjs. Do not edit by hand.

export const PROGRAM_ADDRESS = "Dwd7DXUQHRJaj1suYz6fTcVW7JJqBFVztg1z77t6Ysg";

export const DISCRIMINATORS = {
  "claim_prize": [157, 233, 139, 121, 246, 62, 234, 235],
  "crack": [196, 252, 76, 139, 68, 46, 178, 32],
  "crack_into_jar": [246, 13, 176, 113, 41, 242, 193, 103],
  "create_envelope": [2, 25, 194, 180, 238, 31, 234, 20],
  "create_jar": [79, 12, 25, 249, 245, 177, 203, 232],
  "deposit": [242, 35, 198, 137, 82, 225, 242, 182],
  "deposit_gas": [164, 223, 20, 23, 50, 107, 168, 108],
  "finalize_draw": [112, 9, 234, 94, 99, 176, 12, 181],
  "fund_jar": [7, 109, 53, 116, 129, 46, 10, 55],
  "harvest": [228, 241, 31, 182, 53, 169, 59, 199],
  "initialize": [175, 175, 109, 31, 13, 152, 155, 237],
  "redraw": [86, 111, 66, 164, 105, 158, 114, 164],
  "reimburse_relayer": [64, 245, 110, 83, 237, 199, 182, 206],
  "request_draw": [22, 180, 8, 81, 47, 21, 86, 159],
  "set_paused": [91, 60, 125, 192, 176, 225, 166, 218],
  "set_relayer": [23, 243, 33, 88, 110, 84, 196, 37],
  "sweep_envelope": [44, 157, 60, 235, 95, 141, 15, 71],
  "withdraw": [183, 18, 70, 156, 148, 109, 161, 34],
  "withdraw_gas": [35, 60, 150, 196, 226, 110, 54, 45],
};
